logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
#    org.springframework.boot.autoconfigure: DEBUG

#spring:
#  thymeleaf:
#    cache: false
#  security:
#    oauth2:
#      client:
#        registration:
#          client-id:
#            client-id: c455b613a6f4f08d5ea0
#            client-secret: 1eb0303f79ee93888c646767e99ad4f745673152
#            redirect-uri: "http://localhost:8080/login/oauth2/code/client-id"
#            provider: github
#            scope: read:user,public_repo
##        provider:
#
#resource-uri: https://api.github.com/user/repos

oauth2:
  server:
#    host: https://localhost:443
    host: https://onekey-test.zhejianglab.com

spring:
  thymeleaf:
    cache: false
  security:
    oauth2:
      client:
        registration:
          maxkey:
            client-id: a4fe5396-0aff-40fd-99ac-48115f6f0297
            client-secret: XgsBMzAxMDIwMjAxMzUwNTg2OTM2IA
            authorization-grant-type: authorization_code
            redirect-uri: "http://localhost:8080/login/oauth2/code/maxkey"
            client-authentication-method: post
            scope: all,profile
        provider:
          maxkey:
            authorization-uri: ${oauth2.server.host}/maxkey/oauth/v20/authorize
            token-uri: ${oauth2.server.host}/maxkey/oauth/v20/token
#            user-info-uri: ${oauth2.server.host}/maxkey/api/connect/v10/userinfo
            user-info-uri: ${oauth2.server.host}/maxkey/api/oauth/v20/me
            user-info-authentication-method: header
            user-name-attribute: realname
#            authorization-uri: https://onekey-test.zhejianglab.com/maxkey/oauth/v20/authorize
#            token-uri: https://onekey-test.zhejianglab.com/maxkey/oauth/v20/token
#            user-info-uri: https://onekey-test.zhejianglab.com/maxkey/api/connect/v10/userinfo
#            user-info-authentication-method: header
#            user-name-attribute: name

resource-uri: http://localhost:8080/
